### ISSUE TITLE
Print Variable after tape has been backwarded

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/tape#29]
There is a common user scenario that user may want to print the value of a grad var after running backward pass. 

``` cpp
tape.Backward(loss)
LOG(INFO) << input->Grad().value();
```

However, since Value() will invoke `tape.Forward()` and Foward() will throw when the tape has been forwarded, so the above code will throw.

**Comment by tonyyang-svail** [comment]
@kexinzhao Thanks, this is a good catch.
