### ISSUE TITLE
Benchmark on VGG

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/tape#55]
Goal: evaluate the cost of constructing a tape in every iteration.

Before benchmark, make sure the model can be trained to converge.

Metrics:
- Thoughput (pics/sec), under different batch sizes, different devices.
    - average over 1000 iterations

Model configuration [[fluid](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/models/vgg.py), tape]

**Comment by kexinzhao** [comment]
Vgg16 cifar10 on tape has been tested to be able to train to 90% accuracy on test set.

Throughput (pics/sec) averages over 1000  iterations (actually run 1050 iterations, and skip the first 50 iters).  Code is [here](https://github.com/kexinzhao/tape/tree/benchmark).

Titan Xp on cifar10 (3 x 32 x 32)

|Batch size |     fluid (pics/sec)   |   tape (pics/sec)   |
|---------------|----------:|----------:|
|       1         |   126.5   |   71.0   |
|       2         |   238.0   |  129.5  |
|       4         |  455.0  |  285.8  |
|       8         |  719.1  |  518.9  |
|      16        |  308.1  |  313.6  |
|      32        |  686.6  |  627.6  |
|      64        |  763.9  |  750.1  |
|     128       |  821.4  |  820.0  |
|     256       | 2887.1 | 2798.6 |
|     512       | 2920.2 | 2884.8 |

**Comment by kexinzhao** [comment]
Throughput (pics/sec) averages over 1000  iterations (actually run 1050 iterations, and skip the first 50 iters).

Titan Xp on cifar10 (3 x 32 x 32)

|Batch size |    fluid   |   tape   |
|---------------|----------:|----------:|
|       1         |   48.3   |   69.1   |
|       2         |   86.2   |  127.9  |
|       4         |  166.7  |  255.8  |
|       8         |  383.9  |  440.8  |
|      16        |  256.7  |  280.4  |
|      32        |  560.7  |  619.5  |
|      64        |  682.0  |  715.6  |
|     128       |  764.4  |  793.2  |
|     256       | 2497.2 | 2534.3 |
|     512       | 2714.7 | 2603.6 |
